// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sodxwlkljlbfqylycshb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvZHh3bGtsamxiZnF5bHljc2hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzMTc3ODgsImV4cCI6MjA4Njg5Mzc4OH0.tJ3E3aLx3YuD9Wi5M8EY29U-t3E__-PT-NsNkko7mqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});